### PR TITLE
Schema definition

### PR DESCRIPTION
**Pull request by lasseebert**
First take at a schema definition. I wil continue to work on the currently skipped tests, but I thought I would share what I have so far ;)

It is now possible to do e.g.

```elixir
require Validation.Schema

schema = Validation.Schema.define do
  optional(:first_name, filled and string)
  required(:last_name, filled and string)
end
```

Will give the following data structure:

```elixir
%Validation.Schema{
  rules: %{
    first_name: %Validation.Rule{
      field: :first_name,
      key_rule: :optional,
      value_predicates: {
        :and,
        {:filled, []},
        {:string, []}
      }
    },
    last_name: %Validation.Rule{
      field: :last_name,
      key_rule: :required,
      value_predicates: {
        :and,
        {:filled, []},
        {:string, []}
      }
    }
  }
}
```

### CODE REVIEW

**Comment by lasseebert** [comment]
Would it be better if the `rules` field of a `%Schema{}` was a list instead of a map? That way it would probably be simpler to implement rules that depend on multiple fields.

**Comment by lasseebert** [comment]
Also: The predicate function names should end with a `?`

**Comment by solnic** [comment]
Yes that's a nice convention

**Comment by lasseebert** [comment]
Changed data structure a bit and added handling of arguments to predicates:

``` elixir
iex(2)> Validation.Schema.define do                           
...(2)>   optional(:name, filled? and string?)                  
...(2)>   required(:email, filled? and string? and match?(~r/@/))
...(2)> end
%Validation.Schema{
  rules: [
    %Validation.Rule{
      field: :name,
      key_rule: :optional,
      value_predicates: {
        :and,
        {:filled?, []},
        {:string?, []}
      }
    },
    %Validation.Rule{
      field: :email,
      key_rule: :required,
      value_predicates: {
        :and,
        {
          :and,
          {:filled?, []},
          {:string?, []}
        },
        {:match?, [~r/@/]}
      }
    }
  ]
}
```

**Comment by lasseebert** [comment]
Merging this and start working on a `Validation.result` function ;)

**Pull request merged**
